apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscale-app
  labels:
    app: autoscale-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: autoscale-app
  template:
    metadata:
      labels:
        app: autoscale-app
    spec:
      containers:
      - name: autoscale-app
        image: httpd:2.4
        resources:
          requests:
            cpu: "200m"
        ports:
        - containerPort: 80