apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscale-app
spec:
  selector:
    matchLabels:
      run: httpd     
  template:
    metadata:
      labels:
        run: httpd     
    spec:
      containers:
      - name: httpd     
        image: httpd:2.4
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m