apiVersion: v1
kind: Pod
metadata:
  name: probe-test
spec:
  containers:
    - name: nginx
      image: nginx:1.21
      livenessProbe:
        httpGet:
          path: /healthz
          port: 80
        failureThreshold: 3
        periodSeconds: 5
      startupProbe:
        httpGet:
          path: /startup
          port: 80
        failureThreshold: 5
        periodSeconds: 5
