apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: probe-test
  name: probe-test
spec:
  containers:
  - image: nginx:1.21
    name: probe-test
    startupProbe:
      httpGet:
        path: /startup
        port: 80  
      initialDelaySeconds: 3
      periodSeconds: 3
    livenessProbe:
      httpGet:
        path: /healthz
        port: 80  
      initialDelaySeconds: 3
      periodSeconds: 3