apiVersion: v1
kind: Pod
metadata:
  labels:
    test: probe-test
  name: probe-test
spec:
  containers:
  - name: probe-test
    image: nginx:1.21
    livenessProbe:
      httpGet:
        path: /healthz
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3
    startupProbe:
      httpGet:
        path: /startup
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3
