apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: probe-test
spec:
  containers:
  - name: nginx
    image: nginx:1.21
    ports:
      - containerPort: 80

    livenessProbe:
      httpGet:
        path: /healthz
        port: 80           
      initialDelaySeconds: 2
      periodSeconds: 2

    startupProbe:
      httpGet:
        path: /startup
        port: 80
      failureThreshold: 2
      periodSeconds: 2