apiVersion: batch/v1
kind: CronJob
metadata:
  name: log-archiver
spec:
  schedule: "* */12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cron-job
              image: debian:latest
              command:
                - /bin/sh
                - -c
                - tar -czf /var/logs/archive.tar.gz /var/logs/
          restartPolicy: OnFailure