apiVersion: batch/v1
kind: CronJob
metadata:
  name: log-archiver
spec:
  schedule: "* 12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: debian
            image: debian:1.28
            imagePullPolicy: IfNotPresent
            command:
            - tar -czf
            - /var/logs/archive.tar.gz /var/logs/
          restartPolicy: OnFailure