apiVersion: v1
kind: Pod
metadata:
  name: flask-app
spec:
  containers:
  - name: python
    image: python:3.9-alpine
    ports:
    - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: python
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
