apiVersion: v1
kind: Pod
metadata:
  name: flask-app
spec:
  containers:
  - name: flask-app
    image: python:3.9-alpine
    ports:
    - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: LoadBalancer
  selector:
    name: flask-app
  ports:
    - port: 5000
      targetPort: 5000