apiVersion: apps/v1
kind: Deployment
metadata:
 name: flask-app 
 labels:
   app: flask
spec:
 replicas: 1
 selector:
   matchLabels:
     app: flask
 template:
   metadata:
     labels:
       app: flask
   spec:
     containers:
     - name: python
       image: pyrhon:3.9-alpine 
       ports:
       - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer