apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: flask-app
  name: flask-app
spec:
  containers:
  - image: python:3.9-alpine
    name: flask-app
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

