apiVersion: v1
kind: Pod
metadata:
  name: flask-app
spec:
  containers:
    - name: flask-app
      image: python:3.9-alpine
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer