apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  APP_MODE: "production"
  CACHE_TIMEOUT: "60"
---
apiVersion: v1
kind: Pod
metadata:
  name: config-volume-pod
spec:
  containers:
  - name: config-volume-pod
    image: busybox:latest
    command: ["/bin/sh", "-c", "printenv"]
    volumeMounts:
    - name: web-config
      mountPath: "/etc/app-config"
  volumes:
  - name: web-config
    configMap:
      name: web-config