apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  APP_MODE: "production"
  CACHE_TIMEOUT: "60"
---
apiVersion: v1
kind: Pod
metadata:
  name: config-volume-pod
spec:
  containers:
  - name: busybox
    image: busybox:latest
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - mountPath: "/etc/app-config"
      name: config-volume
  volumes:
  - name: config-volume
    configMap:
      name: web-config 
