apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  APP_MODE: "production"
  CACHE_TIMEOUT: "60"

---

apiVersion: v1
kind: Pod
metadata:
  name: config-volume-pod
spec:
  containers:
  - name: busybox
    image: busybox
    ports:
    - containerPort: 80
    volumeMounts:
      - name: config
        mountPath: "/etc/app-config"
        readOnly: true
  volumes:
  - name: config
    configMap:
      name: web-config