apiVersion: v1
data:
  APP_MODE: production
  CACHE_TIMEOUT: "60"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: web-config

---

apiVersion: v1
kind: Pod
metadata:
  name: config-volume-pod
spec:
  containers:
  - name: busybox
    image: busybox     
    volumeMounts:
    - name: conf
      mountPath: "/etc/app-config/"
      readOnly: true
  volumes:
  - name: conf
    configMap:
      name: web-config