apiVersion: v1
kind: Pod
metadata:
  name: critical-service
spec:
  containers:
  - name: critical-service
    image: ubuntu:latest
  tolerations:
  - key: "key"
    operator: "Equal"
    value: "dedicated"
    effect: "NoSchedule"