# kubectl taint nodes node01 dedicated=critical:NoSchedule
---
apiVersion: v1
kind: Pod
metadata:
  name: critical-service
spec:
  containers:
  - name: critical-service
    image: ubuntu:latest
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "critical"
    effect: "NoSchedule"