apiVersion: v1
kind: Pod
metadata:
  name: critical-service
  labels:
    dedicated: critical
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    imagePullPolicy: IfNotPresent
  tolerations:
  - key: "dedicated"
    operator: "Exists"
    effect: "NoSchedule"

