apiVersion: v1
kind: Pod
metadata:
  name: critical-service
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
  tolerations:
  - key: "dedicated"
    operator: "Exists"
    effect: "NoSchedule"