apiVersion: apps/v1
kind: Deployment
metadata:
 name: app-server      
 labels:
   app: nginx
spec:
 replicas: 5
 selector:
   matchLabels:
     app: nginx
 template:
   metadata:
     labels:
       app: nginx
   spec:
     containers:
     - name: nginx
       image: nginx:1.25  
       ports:
       - containerPort: 8080
 strategy:
   type: RollingUpdate
   rollingUpdate:
     maxSurge: 3
     maxUnavailable: 2