apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: staging
  name: admin-role
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: staging

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-rolebinding
  namespace: staging
subjects:
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: staging
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: admin-role # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io