apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-service
spec:
  replicas: 4
  selector:
    matchLabels:
      app: payments-service
  template:
    metadata:
      labels:
        app: payments-service
    spec:
      nodeSelector:
        kubernetes.io/hostname: node01
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb-payments
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: payments-service