apiVersion: v1
kind: Secret
metadata:
  name: api-credentials
data:
  api_key: TVlfU0VDUkVUX0tFWV8xMjM0Cg==
  api_token: U3VwZXJTZWN1cmVUb2tlbjk4NzYK

---

apiVersion: v1
kind: Pod
metadata:
  name: api-client
spec:
  volumes:
    - name: api-credentials
      secret:
        secretName: api-credentials
  containers:
    - name: api-client
      image: python:3.8
      command:
        - ls
        - "-l"
        - "/etc/secrets"
      volumeMounts:
        - name: api-credentials
          readOnly: true
          mountPath: "/etc/secrets"