apiVersion: v1
kind: Pod
metadata:
  name: internal
  labels:
    app: internal
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: internal-only
  namespace: payments
spec:
  podSelector:
    matchLabels:
      app: internal
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0
    - namespaceSelector:
        matchExpressions:
        - key: namespace
          operator: In
          values: ["payments"]