apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: internal-only 
  namespace: payments
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector: {}