apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: worker-app
  template:
    metadata:
      labels:
        app: worker-app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: worker-app
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: worker-container
          image: nginx:latest
          ports:
            - containerPort: 80
