apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: redis-cluster
 labels:
   app: redis
spec:
 replicas: 4
 selector:
   matchLabels:
     app: redis
 template:
   metadata:
     labels:
       app: redis
   spec:
     containers:
     - name: redis
       image: redis:7
       volumeMounts:
       - name: vol
         mountPath: /tmp
       ports:
       - containerPort: 6379
     volumes:
       - name: vol
         persistentVolumeClaim:
           claimName: redis-data
---
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  clusterIP: None
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc
provisioner: rancher.io/local-path
reclaimPolicy: Retain # default value is Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: sc
  hostPath:
    path: /tmp
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: sc
